version: "3"

services:
  web:
    container_name: cravers_web_app
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./cravers:/site/cravers

  ubuntu:
    container_name: cravers_ubuntu_container
    image: ubuntu
