# Generated by Django 4.1.1 on 2022-10-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('url', models.URLField(max_length=150, verbose_name='Ссылка')),
                ('photo', models.ImageField(upload_to='social_networks/', verbose_name='Фотография')),
            ],
        ),
    ]
