# Generated by Django 4.1.1 on 2022-10-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_menu_field',
            field=models.BooleanField(default=1, verbose_name='Это категория меню?'),
            preserve_default=False,
        ),
    ]
