# Generated by Django 4.1.1 on 2022-10-04 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_is_menu_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('photo', models.FileField(upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['img', 'svg', 'png', 'jpeg', 'ico', 'webp', 'jpg'], message='Этот формат фотографии не подходит')], verbose_name='Фотография')),
                ('photo_back', models.FileField(blank=True, null=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['img', 'svg', 'png', 'jpeg', 'ico', 'webp', 'jpg'], message='Этот формат фотографии не подходит')], verbose_name='Обратная фотография')),
                ('sale', models.PositiveIntegerField(blank=True, default=0, verbose_name='Скидка')),
                ('stars', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, max_length=1, verbose_name='Звёзды')),
                ('is_on_closeout', models.BooleanField(verbose_name='На распродаже?')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
