# Generated by Django 4.1.1 on 2022-10-04 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxLengthValidator(limit_value=99, message='Максимум 99% скидка')], verbose_name='Скидка'),
        ),
    ]
