# Generated by Django 4.1.1 on 2022-10-02 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['img', 'svg', 'png', 'jpeg', 'ico', 'webp'], message='Этот формат фотографии не подходит')], verbose_name='Фотография'),
        ),
    ]
