# Generated by Django 4.1.1 on 2022-10-04 16:44

from django.db import migrations, models
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_description_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[shop.models.product.validate_even], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=1, verbose_name='Звёзды'),
        ),
    ]
