# Generated by Django 4.1.1 on 2022-10-03 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_menucategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='photo',
            field=models.FileField(default=1, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['img', 'svg', 'png', 'jpeg', 'ico', 'webp'], message='Этот формат фотографии не подходит')], verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
