# Generated by Django 4.1.1 on 2022-10-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productoftheday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoftheday',
            options={'verbose_name': 'Продукт дня', 'verbose_name_plural': 'Продукты дня'},
        ),
        migrations.AddField(
            model_name='productoftheday',
            name='open',
            field=models.BooleanField(default=1, verbose_name='Открыта?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoftheday',
            name='sold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продано'),
        ),
    ]
