# Generated by Django 4.1.1 on 2022-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_bestproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.CharField(max_length=60, verbose_name='Описание')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('photo', models.ImageField(upload_to='our_services/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
    ]
