# Generated by Django 4.1.2 on 2022-10-08 15:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locate', models.CharField(max_length=150, verbose_name='Расположен')),
                ('phone', phone_field.models.PhoneField(help_text='Телефон', max_length=31)),
                ('email', models.EmailField(max_length=254, verbose_name='Емейл')),
            ],
            options={
                'verbose_name': 'Контактную запись',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
