# Generated by Django 4.1.2 on 2022-10-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('url', models.URLField(max_length=100, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
    ]
