# Generated by Django 4.1.2 on 2022-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_popularcategory_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='our_services/', verbose_name='Фотография')),
                ('description', models.CharField(max_length=150, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Свидетельство',
                'verbose_name_plural': 'Свидетельство',
            },
        ),
    ]
