# Generated by Django 4.1.2 on 2022-10-09 11:27

from django.db import migrations, models
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_lowerbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerbanner',
            name='sale',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[shop.models.product.validate_even], verbose_name='Скидка'),
        ),
    ]
