# Generated by Django 4.1.2 on 2022-10-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_lowerbanner_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDirectoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product', models.ManyToManyField(related_name='brand_products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Категория Бренда',
                'verbose_name_plural': 'Категории Брендов',
            },
        ),
    ]
