# Generated by Django 4.1.2 on 2022-10-10 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='photo',
            field=models.FileField(upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['img', 'svg', 'png', 'jpeg', 'ico', 'webp', 'jpg'], message='Этот формат фотографии не подходит')], verbose_name='Логотип'),
        ),
    ]
